version: '3.8'

services:
  db:
    image: postgres:16
    container_name: whiteboard_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whiteboard_app
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USER: postgres
      DB_PASS: 12345
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
